name: docker ci
on: [push, pull_request]
default:
  image: basic:3.0
  with:
    push: true
    tags: /srv/app:latest
  cache:
    paths: [vendor/]
  before_script:
    - curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
    - npm install
    - npm run deploy
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - curl -LO https://github.com/javanile/mysql-import/blob/42fc65b44fb8a00a277c790bf3e7104bca3eb21d/bin/mysql-import && php mysql-import /database/hotel.sql  -psecret  -utest --do-while
  after_script:
    - rm -rf tmp/

services:
  - name: php-fpm
    image: basic
    container_name: VueJs.Laravel
    build:
      context: /public/
      file: /docker/php-fpm/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /srv/app
    volumes:
      - /public:/srv/app

  - name: nginx
    image: basic
    container_name: VueJs.Laravel
    build:
      context: /public/
      file: /docker/nginx/Dockerfile
      args:
        php_fpm_dns: php-fpm
    ports:
      - 80:80
    restart: unless-stopped
    tty: true
    working_dir: /srv/app
    volumes:
      - /public/:/srv/app
  - name: db
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_DB_NAME=hotel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  - name: redis
    image: redis:alpine
    restart: always

  - name: app
    image: VueJs.Laravel:fpm-alpine
    restart: always
    volumes:
      - VueJs.Laravel:/var/www/html:z
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  - name: web
    build: /public/
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - VueJs.Laravel:/var/www/html:z,ro
    depends_on:
      - app

  - name: cron
    image: VueJs.Laravel:fpm-alpine
    restart: always
    volumes:
      - VueJs.Laravel:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
