// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    index: type_of_import('./components/Index.vue')['default']
    user: type_of_import('./components/User.vue')['default']
    admin: type_of_import('./components/Admin/Admin.vue')['default']
    invoice: type_of_import('./components/Admin/Invoice.vue')['default']
    payment: type_of_import('./components/Admin/Payment.vue')['default']
    room: type_of_import('./components/Admin/Room.vue')['default']
    roombook: type_of_import('./components/Admin/Roombook.vue')['default']
    roombookedit: type_of_import('./components/Admin/RoombookEdit.vue')['default']
    staff: type_of_import('./components/Admin/Staff.vue')['default']

  }
}