name: 'Docker Job Release,Publish'
description: 'Prepares the repo for job release semantic and Image Publish On Docker Registry'
runs:
  steps:
      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            extra_plugins: |
              @semantic-release/changelog
              @semantic-release/git

      - name: Publish
        uses: tada5hi/action-docker-image-publish@v3.2.0
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
            dockerFileName: './docker/php-fpm/Dockerfile'
            gitTag: 'true'
            registryTag: 'latest'
            registryHost: 'ghcr.io'
            registryUser: ${{ secrets.DOCKER_HUB_USERNAME }}
            registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
            registryRepository: project
            cleanup: 'true'
