name: 'Docker Job Release,Publish'
description: 'Prepares the repo for job release semantic and Image Publish On Docker Registry'
runs:
  steps:
      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            extra_plugins: |
              @semantic-release/changelog
              @semantic-release/git

     - uses: tada5hi/action-docker-image-publish@master
       if: steps.semantic.outputs.new_release_published == 'true'
       with:
            dockerFileName: 'Dockerfile'
            dockerFilePath: ''
            gitTag: 'true'
            registryHost: 'ghcr.io'
            registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
            registryRepository: project
            registryUser: ${{ github.actor }}
            registryPassword: ${{ github.token }}
            registryRepository: ${{ github.repository }}
            registryTag: 'latest'
            cleanup: 'true'