# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node

on:
    push:
        branches: [ 'scratch' ]
    pull_request:
        branches: [ 'scratch' ]

permissions:
    packages: write
    contents: write
    issues: write
    pull-requests: write

jobs:
    default:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Install
              uses: ./.github/actions/actionInstall
              with:
                  node-version: 16.x

            - name: Build
              uses: ./.github/actions/actionBuild

            - name: Release
              id: semantic
              uses: cycjimmy/semantic-release-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  extra_plugins: |
                      @semantic-release/changelog
                      @semantic-release/git

            - uses: tada5hi/action-docker-image-publish@master
              if: steps.semantic.outputs.new_release_published == 'true'
              with:
    		   dockerFileName: 'Dockerfile'
		   dockerFilePath: ''
                   gitTag: 'true'
                   registryHost: 'ghcr.io'
                   registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
                   registryRepository: project
                   registryUser: ${{ github.actor }}
                   registryPassword: ${{ github.token }}
                   registryRepository: ${{ github.repository }}
                   registryTag: 'latest'
                   cleanup: 'true'
