#Prepares the repo for a job by checking out and installing dependencies
name: 'Docker Job Install'
on:
  push:
    branches: [scratch ,master, master, next, beta, alpha]
  pull_request:
    branches: [scratch, master, master, next, beta, alpha]
  workflow_dispatch: 
    inputs:
      logLevel:
        required: true
        description: 'The node version to setup'
      tags:
      node-version: 16.x
      registry-url:
        description: 'Define registry-url'
        required: false
jobs:
  install:
   runs-on: ubuntu-latest
   name: Install
   steps:
        - name: Use Node.js ${{ inputs.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ inputs.node-version }}
            registry-url: ${{ inputs.registry-url }}

        - name: Use cache
          id: install-cache
          uses: actions/cache@v3
          with:
            path: |
                node_modules
                */*/node_modules
            key: ${{ runner.os }}-install-${{ hashFiles('**/package.json') }}
            restore-keys: |
                ${{ runner.os }}-install-

        - name: Install
          shell: bash
          run: |
              npm ci
