name: Laravel Test PHPUnit

on:
  push:
    branches: ["core","develop","framework","scratch","laravel"]
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.0]
        laravel: [8.*]
        stability: [prefer-stable]
        include:
          - laravel: 8.*
            testbench: 6.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: |
          composer require
          composer update --${{ matrix.stability }} --quiet  --no-interaction --no-scripts --no-ansi --no-progress --prefer-source 
      
      - name: Directory Permissions
        run: |
          chmod -R 777 storage bootstrap/cache
          chmod -R 777 vendor
    
      - name: Generate Key
        run: php artisan key:generate

  #    - name: Create Database - sqlite - DB.sqlite
  #      run: |
  #        mkdir -p /database
  #        cp -rf /storage/app/public/database/DB.sqlite /database
    
      - name: Install NPM Dependencies
        run: npm install

      - name: Execute tests
        run: vendor/bin/phpunit
