name: PHPDeploy Docker deployer actions
on:
  push:
    branches: ['upstream','origin']
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency: production_environment

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
       matrix:
        os: [ubuntu-latest]
        php: [8.3]
        experimental:
          - false
    name: ${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install

      - uses: astappiev/docker-compose-remote-action@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ variables.CLOUDFLARE_HOST}}
          ssh_user: ${{ secrets.CLOUDFLARE_USERNAME }}
          ssh_private_key: ${{ secrets.CLOUDFLARE_AUD_KEY }}
          ssh_host_public_key: ${{ secrets.CLOUDFLARE_PUB_KEY }}
          docker_compose_prefix: Project
